version: '3.4'
services:
  monitor:
    image: rahnemann/windows-hosts-writer:1.3-nanoserver-1809
    volumes:
      - C:\windows\system32\drivers\etc:C:\driversetc
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
        
  umbraco-demo-starterkit:
    image: antuangiro/umbraco-demo-starterkit:${UMBRACO_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    environment:
      HOST_HEADER: ${HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umbraco-demo-891-starterkit-web.rule=Host(`${HOST}`)"
      - "traefik.http.routers.umbraco-demo-891-starterkit-web.entrypoints=web"
      - "traefik.docker.network=demo"
    networks:
      demo:
        aliases:
          - ${HOST}

networks:
  demo:
    external:
      name: nat

