version: '3.4'
services:
  monitor:
    image: rahnemann/windows-hosts-writer:1.3-nanoserver-1809
    volumes:
      - C:\windows\system32\drivers\etc:C:\driversetc
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
        
  umbraco-demo-marketingsuite-db:
     image: antuangiro/umbraco-demo-marketingsuite-db:${UMBRACO_VERSION}-marketingsuite-${MARKETINGSUITE_VERSION}
     container_name: umbracodemo-marketingsuite-db
     ports:
       - "1433:1433"
     environment:
       SA_PASSWORD: "Password_01"
       ACCEPT_EULA: "Y"
     networks:
       - demo
        
  umbraco-demo-marketingsuite-web:
    image: antuangiro/umbraco-demo-marketingsuite:${UMBRACO_VERSION}-marketingsuite-${MARKETINGSUITE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    environment:
      HOST_HEADER: ${HOST}
    volumes:
      - .\uMarketingSuiteConfig:C:\inetpub\wwwroot\config\uMarketingSuite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umbraco-demo-891-marketingsuite-web.rule=Host(`${HOST}`)"
      - "traefik.http.routers.umbraco-demo-891-marketingsuite-web.entrypoints=web"
      - "traefik.docker.network=demo"
    depends_on:
      - umbraco-demo-marketingsuite-db
    networks:
      demo:
        aliases:
          - ${HOST}

networks:
  demo:
    external:
      name: nat

